### ISSUE TITLE
SENSOR DE NETO CADA HORA

### ISSUE THREAD

**Issue by lmahave** [MiguelAngelLV/balance_neto#30]
Hola Miguel Ángel. Te agradezco enormemente este trabajo. ES GENIAL.
Lo uso en mi instalación solar con batería de 10 Kwh, hasta el punto de que he automatizado que se apoye con batería cuando haya riesgo de salto de ICP. Para ello, en invierno, que es cuando la aerotermia consume a tope, se reserva un porcentaje de la batería, para que apoye cuando haya riesgo de salto. Ando justo con 3.45 Kw y todo eléctrico.
He andado loco para poder tener un sensor que me dé el último neto que apunta la compañía. Con las 3 entidades que se proporcionan es suficiente en la mayoría de los casos, pero quería tener ese dato rápidamente. No lo lograba y como única solución pensé en pedirte que lo incorporaras.

Al final lo he hecho con una automatización que busque el cambio en cualquiera de los dos sensores de energía (importada y exportada) y, en función de cuál dispare, poner esta plantilla sencilla (que es lo que no sabía hacer):

```yaml
target:
  entity_id: input_number.ultimo_balance_neto
data:
  value: >
    {{ ( trigger.to_state.state | float - trigger.from_state.state | float ) |
    round(4) }}
action: input_number.set_value
```

Cambio el orden en exportada e importada, para que dé negativa la importada.
Esa forma de saber el valor que propició el salto y tener el anterior y el nuevo, lo desconocía.

En fin, mi petición te la mantengo: ¿podrías incorporar ese sensor y evitar esa automatización?

Te reitero mi agradecimiento.

Hello Miguel Ángel. I really appreciate this work. IT'S GREAT.
I use it in my solar installation with a 10 Kwh battery, to the point that I have automated it to support itself with the battery when there is a risk of a jump in the ICP. To do this, in winter, which is when the aerothermal energy consumes at its maximum, a percentage of the battery is reserved, so that it supports itself when there is a risk of a jump. I'm just at 3.45 Kw and everything is electric.
I've been going crazy trying to get a sensor that gives me the last net that the company points out. With the 3 entities that are provided it is enough in most cases, but I wanted to have that data quickly. I couldn't do it and as the only solution I thought of asking you to incorporate it.

In the end I did it with an automation that looks for the change in any of the two energy sensors (imported and exported) and, depending on which one triggers, put this simple template (which is what I didn't know how to do):

target:
entity_id: input_number.ultimo_balance_neto
data:
value: >
{{ ( trigger.to_state.state | float - trigger.from_state.state | float ) |
round(4) }}
action: input_number.set_value

I change the order in exported and imported, so that the imported one gives a negative result.
I didn't know about that way of knowing the value that caused the jump and having the previous and the new one.

Anyway, I maintain my request: could you incorporate that sensor and avoid that automation?

I reiterate my thanks.

**Comment by MiguelAngelLV** [comment]
Buenas.

Si he entendido bien, ¿Quieres saber si el balance neto está subiendo o bajando? Para ello puedes usar el ayudante Trend (tendencia). Básicamente será positivo cuando el valor suba y negativo cuando el valor baje (se puede configurar para invertirlo).  

Entiendo que con eso sería suficiente y te quitas la automatización, ¿no?

**Comment by lmahave** [comment]
Gracias, Miguel Ángel.
No exactamente. Eso me daría la tendencia, pero quiero el valor. Está
implícito en tus sensores de energía, pero quiero saber cuánto se ha
contabilizado cada hora (positivo y negativo).

*Luis Carlos Mahave Riaño*

**Comment by tmallafre** [comment]
Una posibilidad es añadir un sensor y crear una automatización que a cada hora en punto menos 6 segundos te envíe el dato mediante una notificación, un mensaje de Telegram, un correo electrónico... pero el consumo que te indique el balance neto no tiene nada que ver con que salte o no el ICP.

**Comment by MiguelAngelLV** [comment]
@lmahave  ¿Te refieres a cuánto ha cambiado desde la última actualización? ¿Tipo «ha subido 0.1kWh» ?

**Comment by lmahave** [comment]
Llevas razón el balance neto no tiene que ver con el ICP. Lo hago de otra
manera. No sé por qué lo he puesto ahi. Lo siento.

En cuanto a la automatización lo hago con un ayudante numérico que me
almacene el valor. De esa forma tomo el último valor. Sí que estaría bien
el tuyo de almacenarlo 6 segundos antes. Lo que pasa es que en ese momento
del cambio de hora aplico una automatización que corrija el balance neto,
si es negativo. Es pequeño, porque hay batería, pero lo provoca la
sincronización del inversor. Intento que no se consuma nada. Llego a 1 Kwh
al mes, en verano.

La automatización funciona perfectamente. La paso. El input es precisamente
donde almaceno el valor.

```yaml
alias: Actualizar Último Balance Neto
triggers:
  - entity_id:
      - sensor.exportacion_neta
    trigger: state
    id: Exportacion
  - trigger: state
    entity_id:
      - sensor.importacion_neta
    id: Importacion
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: Exportacion
        sequence:
          - target:
              entity_id: input_number.ultimo_balance_neto
            data:
              value: >
                {{ ( trigger.to_state.state | float -
trigger.from_state.state |
                float ) | round(4) }}
            action: input_number.set_value
      - conditions:
          - condition: trigger
            id: Importacion
        sequence:
          - target:
              entity_id: input_number.ultimo_balance_neto
            data:
              value: >
                {{ ( trigger.from_state.state | float -
trigger.to_state.state |
                float ) | round(4) }}
            action: input_number.set_value

``` 
*Luis Carlos Mahave Riaño*
