### ISSUE TITLE
Discrepancias con mi solución previa al balance neto.

### ISSUE THREAD

**Issue by amzaldua** [MiguelAngelLV/balance_neto#8]
Hola Miguel Ángel.

Lo primero de todo es darte las gracias por la aportación.

Me he bajado tu integración para compararla con la solución que había yo implantado vía YAML y he visto algunas diferencias reseñables. Mi planteamiento coincide con tus explicaciones pero me gustaría compartir contigo los resultados para ver donde he cometido el error.

Mi solución:

```yaml
template:
  - sensor:
      - name: "Trevina Balance Neto Horario"
        unique_id: trevina_balance_neto_horario
        icon: mdi:transmission-tower
        unit_of_measurement: "kWh"
        state_class: measurement
        state: >
          {% set exportada_hora = states('sensor.trevina_energia_exportada_hora') | float(0) %}
          {% set importada_hora_punta = states('sensor.trevina_energia_importada_hora_punta') | float(0) %}
          {% set importada_hora_valle = states('sensor.trevina_energia_importada_hora_valle') | float(0) %}
          {{ exportada_hora - (importada_hora_punta + importada_hora_valle) | round(3) }}
        availability: "{{ is_number(states('sensor.solaredge_i1_ac_power')) }}"

sensor:
  - platform: integration
    source: sensor.trevina_potencia_importacion
    name: Trevina Energia Importada
    method: left
    unique_id: trevina_energia_importada
    unit_prefix: k
    round: 3
  - platform: integration
    source: sensor.trevina_potencia_exportacion
    name: Trevina Energia Exportada
    method: left
    unique_id: trevina_energia_exportada
    unit_prefix: k
    round: 3

#Creación tramos de tarifas de energía horarios.
utility_meter:
  trevina_energia_importada_hora:
    source: sensor.trevina_energia_importada
    name: Trevina Energia Importada Hora
    unique_id: trevina_energia_importada_hora
    cycle: hourly
    tariffs:
      - punta
      - valle
  trevina_energia_exportada_hora:
    source: sensor.trevina_energia_exportada
    name: Trevina Energia Exportada Hora
    unique_id: trevina_energia_exportada_hora
    cycle: hourly


#Automatizacion seleccion tarifas segun hora:
automation:
  - id: cambio tramos
    alias: Cambio tramos Iberdrola VE
    trigger:
      - platform: time
        at: "01:00:00"
        variables:
          tariff: "valle"
      - platform: time
        at: "07:00:00"
        variables:
          tariff: "punta"
```

En tu integración he metido los sensores sensor.trevina_energia_importada & sensor.trevina_energia_exportada. Si que para mi calculo de los valores hora en el caso de importada he de sumar los valores de todos los tramos que haya definido, pero entiendo que al final es lo mismo.
A continuación mi gráfica donde se aprecian las diferencias que no son pocas.
<img width="1156" alt="Captura de pantalla 2023-08-09 a las 23 31 46" src="https://github.com/MiguelAngelLV/balance_neto/assets/116205677/070207be-e088-4a81-8222-f240b19be8ff">
